//歌曲播放控制器
export const GET_CONTROL_REQUEST = 'GET_CONTROL_REQUEST';
export const GET_CONTROL_SUCCEED = 'GET_CONTROL_SUCCEED';
export const GET_CONTROL_FAILED = 'GET_CONTROL_FAILED';

//获得单曲id
export const GET_SONG_ID_REQUEST = 'GET_SONG_ID_REQUEST';
export const GET_SONG_ID_SUCCEED = 'GET_SONG_ID_SUCCEED';
export const GET_SONG_ID_FAILED = 'GET_SONG_ID_FAILED';

//手机或邮箱登录
export const PHONE_LOGIN_REQUEST = 'PHONE_LOGIN_REQUEST';
export const EMAIL_LOGIN_REQUEST = 'EMAIL_LOGIN_REQUEST';
export const PHONE_LOGIN_SUCCEED = 'PHONE_LOGIN_SUCCEED';
export const EMAIL_LOGIN_SUCCEED = 'EMAIL_LOGIN_SUCCEED';
export const PHONE_LOGIN_FAILURE = 'PHONE_LOGIN_FAILURE';
export const EMAIL_LOGIN_FAILURE = 'EMAIL_LOGIN_FAILURE';